<?php

return [
    'name' => 'AppSetting',
    'icon' => 'c-sidebar-nav-icon fas fa-cog',
    'basic' => [
        'facebook' => env('FACEBOOK', ''),
        'name' => env('APP_NAME', 'BNF Express'),
        'email' => env('APP_EMAIL', 'bnfexpress@gmail.com'),
        'ticket_email' => env('TICKET_EMAIL', 'bnfexpress@gmail.com'),
        'address' => env('APP_ADDRESS', 'No. 391 Waizayantar Road, Za/South Quarter, Thingangyun Township, Yangon, Myanmar.'),
        'phone' => env('APP_PHONE', '+959420077655, +959895711210'),
        'viber_phone' => env('APP_VIBER_PHONE', '+959260056003'),
        'main_logo' => env('MAIN_LOGO', ''),
        'favicon' => env('APP_FAVICON', ''),
        'meta_keywords' => env('META_KEYWORDS'),
        'meta_description' => env('META_DESCRIPTION'),
        'youtubedemo' => env('YOUTUBEDEMO'),
        'map_key' => env('GOOGLE_MAP'),
        'appstore' => env('APPSTORE'),
        'playstore' => env('PLAYSTORE'),
        'app_dollar_rate' => env('APP_DOLLAR_RATE', ''),
        'app_reference_no' => env('APP_REFERENCE_NO', 'BNF'),
        'domain_url' => env('DOMAIN_URL'),
        // 'google-site-verification' => env('GOOGLE_SITE_VERIFICATION', 'zRWQmPvPtr8QOgAL0M-0h7AFuObWCbejzKoFmHNKNjQ'),
    ],

    'payment' => [
        'paylater' => [
            'enable' => env('PAYLATER_ENABLE', ''),
            'paylater_expiry' => env('PAYLATER_EXPIRY', ''),
            'charge_type' => env('PAYLATER_CHARGE_TYPE', ''),
            'charge' => env('PAYLATER_CHARGE', ''),
        ],
        'ok' => [
           'enable' => env('OK_ENABLE', ''),
           'apikey' => env('OK_APIKEY', ''),
           'destination' => env('OK_DESTINATION', ''),
           'merchant_name' => env('OK_MERCHANT_NAME', ''),
           'payment_url' => env('OK_PAYMENT_URL', ''),
           'frontend_url' => env('OK_FRONTEND_URL', ''),
           'charge_type' => env('OK_CHARGE_TYPE', ''),
           'charge' => env('OK_CHARGE', ''),
        ],
        // 'paypal' => [
        //     'enable' => env('PAYPAL_ENABLE', ''),
        //     'payment_url' => env('PAYPAL_PAYMENT_URL', ''),
        //     'email' => env('PAYPAL_EMAIL', ''),
        //     'charge_type' => env('PAYPAL_CHARGE_TYPE', ''),
        //     'charge' => env('PAYPAL_CHARGE', ''),
        // ],
        'paypal' => [
            'enable' => env('PAYPAL_ENABLE', ''),
            'env' => env('PAYPAL_ENV', ''),
            'client_id' => env('PAYPAL_CLIENT_ID', ''),
            'secret' => env('PAYPAL_SECRET', ''),
            'charge_type' => env('PAYPAL_CHARGE_TYPE', ''),
            'charge' => env('PAYPAL_CHARGE', ''),
        ],
        'mpu' => [
            'enable' => env('MPU_ENABLE', ''),
            'version' => env('MPU_VERSION', '6.9'),
            'hash_key' => env('MPU_HASH_KEY', ''),
            'merchant_id' => env('MPU_MERCHANT_ID', ''),
            'frontend_url' => env('MPU_FRONTEND_URL', ''),
            'backend_url' => env('MPU_BACKEND_URL', ''),
            'payment_url' => env('MPU_PAYMENT_URL', ''),
            'charge_type' => env('MPU_CHARGE_TYPE', ''),
            'charge' => env('MPU_CHARGE', ''),
        ],
        'transfer' => [
            'enable' => env('TRANSFER_ENABLE', ''),
            'transfer_1' => env('TRANSFER_1', ''),
            'transfer_2' => env('TRANSFER_2', ''),
            'transfer_3' => env('TRANSFER_3', ''),
            'transfer_4' => env('TRANSFER_4', ''),
            'transfer_5' => env('TRANSFER_5', ''),
            'transfer_6' => env('TRANSFER_6', ''),
            'transfer_7' => env('TRANSFER_7', ''),
            'transfer_8' => env('TRANSFER_8', ''),
            'transfer_9' => env('TRANSFER_9', ''),
            'transfer_10' => env('TRANSFER_10', ''),
            'charge_type' => env('TRANSFER_CHARGE_TYPE', ''),
            'charge' => env('TRANSFER_CHARGE', ''),
        ],
        'onetwothree'   => [
            'enable' => env('ONETWOTHREE_ENABLE', ''),
            'MerchantID' => env('ONETWOTHREE_MERCHANTID', ''),
            'Merchantpassword' => env('ONETWOTHREE_MERCHANTPASSWORD', ''),
            'Version' => env('ONETWOTHREE_VERSION', ''),
            'CurrencyCode' => env('ONETWOTHREE_CURRENCYCODE', ''),
            'CountryCode' => env('ONETWOTHREE_COUNTRYCODE', ''),
            'AgentCode' => env('ONETWOTHREE_AGENTCODE', ''),
            'ChannelCode' => env('ONETWOTHREE_CHANNELCODE', ''),
            'ApiKey' => env('ONETWOTHREE_APIKEY', ''),
            'Url' => env('ONETWOTHREE_URL', ''),
            'charge_type' => env('ONETWOTHREE_CHARGE_TYPE', ''),
            'charge' => env('ONETWOTHREE_CHARGE', ''),
        ],
        'visa_master'   => [
            'enable' => env('VISA_MASTER_ENABLE', ''),
            'version' => env('VISA_MASTER_VERSION', ''),
            'currency' => env('VISA_MASTER_CURRENCY', ''),
            'hash_key' => env('VISA_MASTER_HASH_KEY', ''),
            'merchant_id' => env('VISA_MASTER_MERCHANT_ID', ''),
            'frontend_url' => env('VISA_MASTER_FRONTEND_URL', ''),
            'backend_url' => env('VISA_MASTER_BACKEND_URL', ''),
            'payment_url' => env('VISA_MASTER_PAYMENT_URL', ''),
            'charge_type' => env('VISA_MASTER_CHARGE_TYPE', ''),
            'charge' => env('VISA_MASTER_CHARGE', ''),
        ],
        'truemoney'   => [
            'enable' => env('TRUE_ENABLE', ''),
            'hash_key' => env('TRUE_HASH_KEY', ''),
            'merchant_id' => env('TRUE_MERCHANT_ID', ''),
            'true_url' => env('TRUE_URL', ''),
            'backend_url' => env('TRUE_BACKEND_URL', ''),
            'charge_type' => env('TRUE_CHARGE_TYPE', ''),
            'charge' => env('TRUE_CHARGE', ''),
        ],
        'deposit'   => [
            'enable' => env('DEPOSIT_ENABLE', ''),
            'charge_type' => env('DEPOSIT_CHARGE_TYPE', ''),
            'charge' => env('DEPOSIT_CHARGE', ''),
            'secret_key' => env('DEPOSIT_SECRET_KEY', ''),
        ],
        'wave'   =>  [
            'enable' => env('WAVE_ENABLE', ''),
            'public_key'  =>  env('WAVE_PUBLIC_KEY', ''),
            'private_key' =>  env('WAVE_PRIVATE_KEY', ''),
            'charge_type' => env('WAVE_CHARGE_TYPE', ''),
            'charge' => env('WAVE_CHARGE', ''),
        ],
        'kbz_direct'   => [
            'enable' => env('KBZDIRECTPAY_ENABLE', ''),
            'client_code' => env('KBZDIRECTPAY_CLIENT_CODE', ''),
            'merchant_code' => env('KBZDIRECTPAY_MERCHANT_CODE', ''),
            'currency_code' => env('KBZDIRECTPAY_CURRENCY_CODE', ''),
            'success_flag' => env('KBZDIRECTPAY_SUCCESS_FLAG', ''),
            'fail_flag' => env('KBZDIRECTPAY_FAIL_FLAG', ''),
            'kbzdirectpay_url' => env('KBZDIRECTPAY_URL', ''),
            'success_url' => env('KBZDIRECTPAY_SUCCESS_URL', ''),
            'failed_url' => env('KBZDIRECTPAY_FAILED_URL', ''),
            'charge_type' => env('KBZDIRECTPAY_CHARGE_TYPE', ''),
            'charge' => env('KBZDIRECTPAY_CHARGE', ''),
        ],
        'cb'   => array(
            'enable' => env('CBPAY_ENABLE', 'true'),
            'merchant_key' => env('CBPAY_MERCHANT_KEY', 'BNFEXKEYS'),
            'merchant_id' => env('CBPAY_MERCHANT_ID', 'BNFEX'),
            'currency' => env('CBPAY_CURRENCY', 'MMK'),
            'common_key' => env('CBPAY_COMMON_KEY', 'CBPAYMENT'),
            'payment_url' => env('CBPAY_PAYMENT_URL', "http://online.cbbank.com.mm/CBPayEnc/servletcontroller"),
            'charge_type' => env('CBPAY_CHARGE_TYPE', 'amount'),
            'charge' => env('CBPAY_CHARGE', '100'),
            'encrypt_salt' => env('CBPAY_ENCRYPT_SALT', "rIkZOJxkiNNUQ2AKGG9wiQM="),
            'encrypt_vector' => env('CBPAY_ENCRYPT_VECTOR', "TZuWY0W5Yn9l9F2DEiU0hg=="),
        ),

        'mab'   => [
           'enable' => env('MAB_ENABLE', ''),
           'mab_merchantid' => env('MAB_MERCHANTID', ''),
           'mab_sharekey' => env('MAB_SHAREKEY', ''),
           'mab_name' => env('MAB_NAME', ''),
           'mab_url' => env('MAB_URL', ''),
           'mab_frontend_url' => env('MAB_FRONTEND_URL', ''),
           'act_url' => env('MAB_ACT_URL', ''),
           'charge_type' => env('MAB_CHARGE_TYPE', ''),
           'charge' => env('MAB_CHARGE', ''),
        ],

        'bnfcredit'   => [
           'enable' => env('CREDIT_ENABLE', ''),
           'charge_type' => env('CREDIT_CHARGE_TYPE', ''),
           'charge' => env('CREDIT_CHARGE', ''),
        ],

        'topup'   => [
            'enable' => env('TOPUP_ENABLE', 'true'),
            'version' => env('TOPUP_VERSION', '1.0'),
            'appid' => env('TOPUP_APP_ID', 'B9CA18BC-7BEB-4828-AE1A-5CCC13B01CBB'),
            'secretkey' => env('TOPUP_SECRET_KEY', 'd466c07ae0080c0961fa0b5f7a1d66d17e5438978ea76cb48ad31bff7bebf071'),
            'topup_url' => env('TOPUP_URL', 'https://bnftopup.com/transaction'),
            'charge_type' => env('TOPUP_CHARGE_TYPE', 'amount'),
            'charge' => env('TOPUP_CHARGE', '0'),

        ],

        'uab' => [
            'enable' => env('UAB_ENABLE', 'false'),
            'merchant_id' => env('UAB_MERCHANT_ID', ''),
            'merchant_access_key' => env('UAB_MERCHANT_ACCESS_KEY', ''),
            'merchant_channel' => env('UAB_MERCHANT_CHANNEL', ''),
            'secret_key' => env('UAB_SECRET_KEY', ''),
            'ins_id' => env('UAB_INS_ID', '25050004'),
            'client_secret' => env('UAB_CLIENT_SECRET', '6<Oo0YW3{£=h'),
            'payment_method' => env('UAB_PAYMENT_METHOD', 'uabpay,visa_master,mpu,upi'),
            'payment_url' => env('UAB_URL', ''),
            'backend_url' => env('UAB_BACKEND_URL', ''),
            'frontend_success_url' => env('UAB_FRONTEND_SUCCESS_URL', ''),
            'frontend_failed_url' => env('UAB_FRONTEND_FAILED_URL', ''),
            'payment_expire_in_second' => env('UAB_PAYMENT_EXPIRE_IN_SECOND', '420'),
            'charge_type' => env('UAB_CHARGE_TYPE', 'amount'),
            'charge' => env('UAB_CHARGE', '0'),
        ]

    ],

    'email' => [
        'mail_driver' => env('MAIL_MAILER', 'Smtp'),
        'mail_host' => env('MAIL_HOST', 'smtp.mailtrap.io'),
        'mail_port' => env('MAIL_PORT', '587'),
        'mail_username' => env('MAIL_USERNAME', '7d41168bba76b9'),
        'mail_password' => env('MAIL_PASSWORD', '338a6d5b5f94cd'),
        'mail_encryption' => env('MAIL_ENCRYPTION', 'tls'),
    ],

    'sms' => [
        'smspoh_url' => env('SMSPOH_API_URL', 'https://v3.smspoh.com/api'),
        'smspoh_secret' => env('SMSPOH_API_SECRET', 'B2UNHSPmPyrrfcZ4'),
        'smspoh_api_key' => env('SMSPOH_API_KEY', '0UJJQt5Mujq15stK'),
        'smspoh_senderId' => env('SMSPOH_SENDER_ID', 'SMSPoh Demo'),
        'smspoh_max_attempt' => env('SMSPOH_MAX_ATTEMPT', '3'),
        'smspoh_pin_length' => env('SMSPOH_PIN_LENGTH', '6'),
        'smspoh_duration' => env('SMSPOH_DURATION', '60'),
        'smspoh_resend_cooldown' => env('SMSPOH_RESEND_COOLDOWN', '60'),
    ],
];
